// One-off: turn the reference bust into a radius-modulated halftone dot lattice
// of the FACE (cropped head). Emits a HI-RES set (components/brand/bust-dots.ts
// + app/apple-icon.png, used by the wordmark + landing centerpiece) and a COARSE
// set (app/icon.svg, legible as a tiny tab favicon). Writes preview ramps to /tmp.
// Run: node scripts/gen-bust.mjs
import sharp from "sharp";
import { writeFileSync } from "node:fs";

const SRC =
  process.argv[2] ||
  "/Users/yancun/.claude/image-cache/627af931-eccc-4087-9cc1-86b4b3df7798/2.png";

// Crop to the FACE of Socrates (head: forehead → beard), not the whole bust.
const CROP = { left: 70, top: 10, width: 125, height: 120 };
const BG_CUT = 0.17; // darkness below this = background, no dot
const GAMMA = 0.85; // tonal curve for radius
const MAXR = 0.6; // max dot radius in cell units

async function buildDots(GW) {
  const GH = Math.round(GW * (CROP.height / CROP.width));
  const { data } = await sharp(SRC)
    .extract(CROP)
    .greyscale()
    .normalise()
    .resize(GW, GH, { fit: "fill" })
    .raw()
    .toBuffer({ resolveWithObject: true });

  const dots = [];
  let minX = GW, minY = GH, maxX = 0, maxY = 0;
  for (let y = 0; y < GH; y++) {
    for (let x = 0; x < GW; x++) {
      const dark = 1 - data[y * GW + x] / 255;
      if (dark < BG_CUT) continue;
      const r = Math.min(MAXR, Math.pow(dark, GAMMA) * MAXR + 0.06);
      dots.push([+(x + 0.5).toFixed(2), +(y + 0.5).toFixed(2), +r.toFixed(2)]);
      minX = Math.min(minX, x); minY = Math.min(minY, y);
      maxX = Math.max(maxX, x + 1); maxY = Math.max(maxY, y + 1);
    }
  }
  const pad = 0.8;
  const vb = `${(minX - pad).toFixed(2)} ${(minY - pad).toFixed(2)} ${(maxX - minX + pad * 2).toFixed(2)} ${(maxY - minY + pad * 2).toFixed(2)}`;
  const circles = dots.map(([cx, cy, r]) => `<circle cx="${cx}" cy="${cy}" r="${r}"/>`).join("");
  return { GW, GH, vb, dots, circles };
}

function svg(b, fg, bg) {
  const [x, y, w, h] = b.vb.split(" ");
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${b.vb}">${bg ? `<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${bg}"/>` : ""}<g fill="${fg}">${b.circles}</g></svg>`;
}

// ── HI-RES face → bust-dots.ts (wordmark + centerpiece) + apple-icon ──────────
const HI = await buildDots(42);
writeFileSync(
  "components/brand/bust-dots.ts",
  `// AUTO-GENERATED by scripts/gen-bust.mjs — the FACE of Socrates as a hi-res\n// radius-modulated halftone lattice; render each as <circle fill="currentColor">.\nexport const BUST_VIEWBOX = "${HI.vb}";\nexport const BUST_DOTS: [number, number, number][] = ${JSON.stringify(HI.dots)};\n`,
);
console.log(`hi-res ${HI.GW}x${HI.GH} · ${HI.dots.length} dots`);

// apple-icon: hi-res face centered square on paper
{
  const [x, y, w, h] = HI.vb.split(" ").map(Number);
  const side = Math.max(w, h) + 5;
  const ox = x - (side - w) / 2, oy = y - (side - h) / 2;
  const apple = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${ox.toFixed(2)} ${oy.toFixed(2)} ${side.toFixed(2)} ${side.toFixed(2)}"><rect x="${ox.toFixed(2)}" y="${oy.toFixed(2)}" width="${side.toFixed(2)}" height="${side.toFixed(2)}" fill="#F4F6FA"/><g fill="#0B0F1A">${HI.circles}</g></svg>`;
  await sharp(Buffer.from(apple)).resize(180, 180).png().toFile("app/apple-icon.png");
}

// ── COARSE face → icon.svg (tiny tab favicon, prefers-color-scheme) ───────────
const CO = await buildDots(20);
writeFileSync(
  "app/icon.svg",
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${CO.vb}"><style>circle{fill:#0B0F1A}@media (prefers-color-scheme:dark){circle{fill:#E8ECF4}}</style>${CO.circles}</svg>`,
);
console.log(`coarse ${CO.GW}x${CO.GH} · ${CO.dots.length} dots → icon.svg`);

// ── preview ramps (both sets) ─────────────────────────────────────────────────
const SIZES = [180, 96, 48, 32, 16];
const PAD = 22;
async function ramp(b, fg, bgHex, bgObj, out) {
  const s = Buffer.from(svg(b, fg, bgHex));
  const comps = [];
  let x = PAD;
  for (const px of SIZES) {
    comps.push({ input: await sharp(s).resize(px, px, { fit: "contain", background: bgObj }).png().toBuffer(), top: PAD + (180 - px), left: x });
    x += px + PAD;
  }
  await sharp({ create: { width: x, height: 180 + PAD * 2, channels: 3, background: bgObj } }).composite(comps).png().toFile(out);
}
await ramp(HI, "#0B0F1A", "#F4F6FA", { r: 244, g: 246, b: 250 }, "/tmp/bust-hi-light.png");
await ramp(HI, "#E8ECF4", "#0B1220", { r: 11, g: 18, b: 32 }, "/tmp/bust-hi-dark.png");
await ramp(CO, "#0B0F1A", "#F4F6FA", { r: 244, g: 246, b: 250 }, "/tmp/bust-coarse.png");
console.log("previews: /tmp/bust-hi-{light,dark}.png, /tmp/bust-coarse.png");
