// One-off: turn the reference bust image into a radius-modulated halftone dot
// lattice (the dot-matrix logo). Emits components/brand/bust-dots.ts and writes
// preview PNGs to /tmp for visual verification. Run: node scripts/gen-bust.mjs
import sharp from "sharp";
import { writeFileSync } from "node:fs";

const SRC =
  process.argv[2] ||
  "/Users/yancun/.claude/image-cache/627af931-eccc-4087-9cc1-86b4b3df7798/2.png";

const GW = Number(process.argv[3] || 30); // grid width in cells
const BG_CUT = 0.16; // darkness below this = background, no dot
const GAMMA = 0.8; // tonal curve for radius
const MAXR = 0.62; // max dot radius in cell units

const meta = await sharp(SRC).metadata();
const GH = Math.round(GW * (meta.height / meta.width));

const { data } = await sharp(SRC)
  .greyscale()
  .resize(GW, GH, { fit: "fill" })
  .raw()
  .toBuffer({ resolveWithObject: true });

const dots = [];
let minX = GW,
  minY = GH,
  maxX = 0,
  maxY = 0;
for (let y = 0; y < GH; y++) {
  for (let x = 0; x < GW; x++) {
    const lum = data[y * GW + x] / 255;
    const dark = 1 - lum;
    if (dark < BG_CUT) continue;
    const r = Math.min(MAXR, Math.pow(dark, GAMMA) * MAXR + 0.06);
    dots.push([x + 0.5, y + 0.5, r]);
    minX = Math.min(minX, x);
    minY = Math.min(minY, y);
    maxX = Math.max(maxX, x + 1);
    maxY = Math.max(maxY, y + 1);
  }
}

// trim viewBox to the dot bounding box + small padding
const pad = 0.8;
const vb = {
  x: +(minX - pad).toFixed(2),
  y: +(minY - pad).toFixed(2),
  w: +(maxX - minX + pad * 2).toFixed(2),
  h: +(maxY - minY + pad * 2).toFixed(2),
};

const rounded = dots.map(([cx, cy, r]) => [
  +cx.toFixed(2),
  +cy.toFixed(2),
  +r.toFixed(2),
]);

const ts = `// AUTO-GENERATED by scripts/gen-bust.mjs from the reference bust.
// A radius-modulated halftone lattice; render each as <circle fill="currentColor">.
export const BUST_VIEWBOX = "${vb.x} ${vb.y} ${vb.w} ${vb.h}";
export const BUST_DOTS: [number, number, number][] = ${JSON.stringify(rounded)};
`;
writeFileSync("components/brand/bust-dots.ts", ts);
console.log(`grid ${GW}x${GH} · ${rounded.length} dots · viewBox ${BUST_VIEWBOX(vb)}`);
function BUST_VIEWBOX(v) {
  return `${v.x} ${v.y} ${v.w} ${v.h}`;
}

// build a preview SVG and rasterize (light + dark, large + favicon size)
const circles = rounded
  .map(([cx, cy, r]) => `<circle cx="${cx}" cy="${cy}" r="${r}"/>`)
  .join("");
function svg(fg, bg) {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${vb.x} ${vb.y} ${vb.w} ${vb.h}"><rect x="${vb.x}" y="${vb.y}" width="${vb.w}" height="${vb.h}" fill="${bg}"/><g fill="${fg}">${circles}</g></svg>`;
}
const light = Buffer.from(svg("#0B0F1A", "#F4F6FA"));
const dark = Buffer.from(svg("#E8ECF4", "#0B1220"));
const blue = Buffer.from(svg("#0F62FE", "#F4F6FA"));
await sharp(light).resize(260).png().toFile("/tmp/bust-light.png");
await sharp(dark).resize(260).png().toFile("/tmp/bust-dark.png");
await sharp(blue).resize(260).png().toFile("/tmp/bust-blue.png");
await sharp(light).resize(32).png().toFile("/tmp/bust-32.png");
await sharp(light).resize(16).png().toFile("/tmp/bust-16.png");
// a contact sheet
const sheet = `<svg xmlns="http://www.w3.org/2000/svg" width="600" height="260"><rect width="600" height="260" fill="#fff"/><image href="data:image/png;base64,${(await sharp(light).resize(240).png().toBuffer()).toString("base64")}" x="0" y="10"/><image href="data:image/png;base64,${(await sharp(dark).resize(240).png().toBuffer()).toString("base64")}" x="250" y="10"/><image href="data:image/png;base64,${(await sharp(light).resize(32).png().toBuffer()).toString("base64")}" x="510" y="20"/><image href="data:image/png;base64,${(await sharp(light).resize(16).png().toBuffer()).toString("base64")}" x="510" y="70"/></svg>`;
await sharp(Buffer.from(sheet)).png().toFile("/tmp/bust-sheet.png");
console.log("previews written to /tmp/bust-*.png");

// ── Next.js app icons ────────────────────────────────────────────────────────
// icon.svg: transparent, single-color, flips with the browser chrome theme
const iconSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${vb.x} ${vb.y} ${vb.w} ${vb.h}"><style>circle{fill:#0B0F1A}@media (prefers-color-scheme:dark){circle{fill:#E8ECF4}}</style>${circles}</svg>`;
writeFileSync("app/icon.svg", iconSvg);

// apple-icon: square, bust centered on paper with padding
const side = Math.max(vb.w, vb.h) + 6;
const ox = vb.x - (side - vb.w) / 2;
const oy = vb.y - (side - vb.h) / 2;
const appleSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${ox.toFixed(2)} ${oy.toFixed(2)} ${side.toFixed(2)} ${side.toFixed(2)}"><rect x="${ox.toFixed(2)}" y="${oy.toFixed(2)}" width="${side.toFixed(2)}" height="${side.toFixed(2)}" fill="#F4F6FA"/><g fill="#0B0F1A">${circles}</g></svg>`;
await sharp(Buffer.from(appleSvg)).resize(180, 180).png().toFile("app/apple-icon.png");
console.log("wrote app/icon.svg + app/apple-icon.png");
